### ISSUE TITLE
stable release to snap store

### ISSUE THREAD

**Issue by christianrauch** [sd-hd/sway-snap#1]
Is there a chance that this gets updated to sway 1.2 and released as stable to the snap store?

**Comment by aiqs4** [comment]
well, there is a problem with setting capabilities in snap.

then i found that sway is  already packaged as "deb" since ubuntu 19.04 "disco"

so, currently, I have no reason to continue building the project.


here is a similar problem with cap's:

https://forum.snapcraft.io/t/wireshark-and-setcap/9629


if really needed, i could update the package to a newer source version...

**Comment by aiqs4** [comment]
hello christianrauch,

just updated the snap to a newer version.

Hope i can fix the pcap issue soon.

**Comment by christianrauch** [comment]
Did you manage to run the snap in classic mode?
I was working on getting the snap running with sway 1.2 on my `sway_1.2` branch: https://github.com/christianrauch/sway-snap/blob/sway_1.2/snap/snapcraft.yaml

Feel free to take from my yaml. I believe my snap should result in a smaller package, since it has less dependencies / relies on less packages in the `stage-packages`.

I was not able to build the snap yet, since there is some issue with the `json-c` package within the snap environment. It gets installed properly, but sway parts is unable to find these headers.

**Comment by aiqs4** [comment]
Hi chrisian,

Thank you :-)

Currently i still use --devmode instead of classic.

i just started a thread here: 
https://forum.snapcraft.io/t/sway-an-i3-compatible-wayland-compositor/14277

I could build the snap, but in newer versions it doesn't start. An older version was able to start.

On the forum is a script to repackage the snap with "setcap".

Later i will reduce the stage-packages. It's just experimental, for now ... ;-)

**Comment by tsloughter** [comment]
> so, currently, I have no reason to continue building the project.

Oh, are you not going to continue this because their is a deb package?

**Comment by aiqs4** [comment]
yes, i wanted.

But there was so demand on #snapcraft (freenode)
